Repository migtools/oadp-non-admin, pull requests merged in 2025-02, with the labels that each got.

#163 Remove associated Non Admin Backups during Non Admin BSL removal
  docs/design/non_admin_backupstoragelocation.md
  internal/controller/nonadminbackupstoragelocation_controller.go
Labels: approved, lgtm

#171 Improved error messages for enforced backup/restore spec
  internal/common/function/function.go
  internal/controller/nonadminbackup_controller_test.go
Labels: approved, lgtm

#152 feat: Garbage collector
  cmd/main.go
  go.mod
  go.sum
  internal/common/function/function.go
  internal/controller/garbagecollector_controller.go
  internal/controller/garbagecollector_controller_test.go
  internal/source/periodical_source.go
Labels: approved, lgtm

#180 feat(Makefile): add docker cli image load support so it can later be pushed
  Makefile
Labels: approved, lgtm

#177 add some helpful links to user creation
  docs/non_admin_user.md
Labels: approved, lgtm

#172 Setting NaBSL prefix
  internal/common/function/function.go
  internal/controller/nonadminbackupstoragelocation_controller.go
  internal/controller/nonadminbackupstoragelocation_controller_test.go
Labels: approved, lgtm

#191 Fix for #188 - NaBSL s3 sdk version incompability
  go.mod
  go.sum
  internal/controller/nonadminbackupstoragelocation_controller.go
Labels: approved, lgtm

#138 feat: NonAdminBackup sync controller
  cmd/main.go
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/common/constant/constant.go
  internal/controller/nonadminbackup_controller.go
  internal/controller/nonadminbackup_controller_test.go
  internal/controller/nonadminbackupstoragelocation_controller.go
  internal/controller/nonadminbackupsynchronizer_controller.go
  internal/controller/nonadminbackupsynchronizer_controller_test.go
Labels: approved, lgtm

#196 fix: Garbage collector concurrently
  go.mod
  go.sum
  internal/controller/garbagecollector_controller.go
  internal/controller/garbagecollector_controller_test.go
Labels: approved, lgtm

#208 Add validation error on NAB for restricted spec values
  internal/common/constant/constant.go
  internal/common/function/function.go
  internal/common/function/function_test.go
  internal/controller/nonadminbackup_controller_test.go
Labels: approved, lgtm

#218 fix: restrict VSL spec in NAB
  internal/common/function/function.go
  internal/common/function/function_test.go
Labels: approved, lgtm

#217 fix: show velero backup spec in NonAdminBackup status
  api/v1alpha1/nonadminbackup_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
  internal/controller/nonadminbackup_controller.go
  internal/controller/nonadminbackup_controller_test.go
Labels: approved, lgtm

#182 fix(Makefile): docker-buildx-nac do not add duplicate `--platform`
  Makefile
Labels: approved, lgtm

#216 Approval of the NonAdminBackupStorageLocation
  api/v1alpha1/nonadminbackupstoragelocation_types.go
  api/v1alpha1/nonadminbackupstoragelocationrequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/oadp_v1alpha1_nonadminbackupstoragelocationrequest.yaml
  docs/design/non_admin_backupstoragelocation.md
  go.mod
  go.sum
  internal/common/function/function.go
  internal/common/function/function_test.go
  internal/controller/garbagecollector_controller.go
  internal/controller/garbagecollector_controller_test.go
  internal/controller/nonadminbackupstoragelocation_controller.go
  internal/controller/nonadminbackupstoragelocation_controller_test.go
  internal/handler/nonadminbackupstoragelocationrequest_handler.go
  internal/predicate/composite_nabsl_predicate.go
  internal/predicate/nonadminbackupstoragelocationrequest_predicate.go
Labels: approved, lgtm, priority-critical, feature complete

#227 Add restrictions for non-admin restore spec
  internal/common/constant/constant.go
  internal/common/function/function.go
  internal/common/function/function_test.go
Labels: approved, lgtm, priority-high, feature complete

#229 Exclude certain cluster-scoped resources from non-admin Backups/Restores
  internal/controller/nonadminbackup_controller.go
  internal/controller/nonadminbackup_controller_test.go
  internal/controller/nonadminrestore_controller.go
  internal/controller/nonadminrestore_controller_test.go
Labels: approved, lgtm

#226 LogLevel configuration via dpa env.
  cmd/main.go
  cmd/main_test.go
  go.mod
  internal/common/constant/constant.go
Labels: approved, lgtm

#223 fix: NABSL sync period validation
  cmd/main.go
  internal/common/function/function.go
  internal/common/function/function_test.go
  internal/controller/nonadminbackupstoragelocation_controller.go
  internal/controller/nonadminbackupstoragelocation_controller_test.go
Labels: approved, lgtm

#210 fix: NonAdmin objects associated objects deletion info
  api/v1alpha1/nonadminbackup_types.go
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
  internal/controller/nonadminbackup_controller.go
  internal/controller/nonadminbackup_controller_test.go
  internal/controller/nonadminrestore_controller.go
  internal/controller/nonadminrestore_controller_test.go
  internal/handler/velerobackup_handler.go
  internal/predicate/compositebackup_predicate.go
  internal/predicate/velerobackup_predicate.go
  internal/predicate/velerorestore_predicate.go
Labels: approved, lgtm

#240 Reuse existing buildx builder for cache
  Makefile
Labels: approved, lgtm

#236 Update CRD and logic to enable Non Admin BSL enforcements
  api/v1alpha1/nonadminbackupstoragelocationrequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  docs/design/admin_control_over_spec.md
  go.mod
  go.sum
  internal/common/function/function.go
  internal/common/function/function_test.go
  internal/controller/garbagecollector_controller.go
  internal/controller/garbagecollector_controller_test.go
  internal/controller/nonadminbackupstoragelocation_controller.go
  internal/controller/nonadminbackupstoragelocation_controller_test.go
Labels: approved, lgtm
