Repository migtools/oadp-non-admin, pull requests merged in 2025-04, with the labels that each got.

#260 OADP-5799:Allow users to set NAC logging to json format
  cmd/main.go
  cmd/main_test.go
  internal/common/constant/constant.go
Labels: approved, lgtm, jira/valid-reference

#262 fix: CI branches
  .github/workflows/ci.yml
Labels: approved, lgtm

#257 fix: envtest version for OCP 4.19
  Makefile
  internal/controller/suite_test.go
Labels: approved, lgtm

#245 CRD updates for the oc CLI fields for the NAR, NAB and NABSL objects
  api/v1alpha1/nonadminbackup_types.go
  api/v1alpha1/nonadminbackupstoragelocation_types.go
  api/v1alpha1/nonadminbackupstoragelocationrequest_types.go
  api/v1alpha1/nonadmindownloadrequest_types.go
  api/v1alpha1/nonadminrestore_types.go
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocations.yaml
  config/crd/bases/oadp.openshift.io_nonadmindownloadrequests.yaml
  config/crd/bases/oadp.openshift.io_nonadminrestores.yaml
Labels: approved, lgtm, feature complete

#244 Add reconcile of the NaBSL upon Secret creation in a given namespace
  internal/controller/nonadminbackupstoragelocation_controller.go
  internal/handler/nonadminbsl_secret_handler.go
  internal/predicate/composite_nabsl_predicate.go
  internal/predicate/nonadminbsl_secret_predicate.go
Labels: approved, lgtm, feature complete

#272 Update OADP Operator dep
  go.mod
  go.sum
Labels: approved, lgtm

#264 fix: update golangci-lint
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  internal/common/function/function.go
  internal/controller/nonadminbackup_controller.go
  internal/controller/nonadminbackupstoragelocation_controller.go
Labels: approved, lgtm

#271 Update OADP Operator dep to 1.5
  go.mod
  go.sum
Labels: approved, lgtm

#274 v1.5: Add downstream Dockerfile
  Dockerfile.oadp
Labels: approved, lgtm
